[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Kill Netlify badge pill 100%
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
